CES-Maybe/Demo-Project-Farm

web/config/commerce_store.commerce_store_type.local_sto.yml, web/config/core.entity_form_display.commerce_product_variation.default.default.yml, web/config/core.entity_form_display.commerce_store.online.default.yml, web/config/core.entity_form_display.user.user.default.yml, web/config/core.entity_view_display.commerce_product_variation.default.summary.yml, web/config/core.entity_view_display.commerce_product_variation.default.wishlist.yml, web/config/core.entity_view_display.commerce_store.online.default.yml, web/config/core.entity_view_display.node.page.default.yml, web/config/core.entity_view_display.user.user.compact.yml, web/config/core.entity_view_display.user.user.default.yml, web/config/field.field.commerce_product.default.field_images.yml, web/config/field.field.commerce_store.online.field_description.yml, web/config/field.field.commerce_store.online.field_image_store.yml, web/config/field.field.user.user.field_address.yml, web/config/field.storage.commerce_product.field_images.yml, web/config/field.storage.commerce_store.field_description.yml, web/config/field.storage.commerce_store.field_image_store.yml, web/config/field.storage.user.field_address.yml, web/config/page_manager.page_variant.home-panels_variant-0.yml
Add necessary fields for farms and customers
=> feat: create farm and customer type

.eslintignore, .github/workflows/code-style.yaml, .gitignore, .husky/pre-commit, .lando.yml, .prettierignore, .stylelintignore, commitlint.config.js, composer.json, composer.lock, package-lock.json, package.json, phpunit.xml, web/modules/custom/farm_page/farm_page.info.yml, web/modules/custom/farm_page/farm_page.libraries.yml, web/modules/custom/farm_page/farm_page.module, web/modules/custom/farm_page/farm_page.permissions.yml, web/modules/custom/farm_page/farm_page.routing.yml, web/modules/custom/farm_page/src/Controller/FarmPageController.php, web/scripts/codestyle/config.sh
Test gitflow phpcbf
CU-865d2jr0k
=> feat: test gitflow phpcbf

web/themes/custom/sshop/css/custom.css, web/themes/custom/sshop/sshop.theme, web/themes/custom/sshop/templates/system/html--admins--farmers-list.html.twig
create a list for site admin to view and take action on farmers account
=> feat: create admin list views farmers

.github/workflows/deploy.yaml
=> feat: update ci/cd

.github/workflows/deploy.yaml
Test deploy workflow
CU-865d2jr0k
=> feat: test deploy workflow

composer.json, composer.lock
=> feat: update site dev

config/user_redirect.settings.yml
set up config to navigate every user with role farmer to appointed page
CU-865czvvfq
=> feat: create default navigation for farmer

web/modules/custom/maybe_forms/maybe_forms.info.yml, web/modules/custom/maybe_forms/maybe_forms.module, web/modules/custom/maybe_forms/maybe_forms.routing.yml, web/modules/custom/maybe_forms/maybe_forms.services.yml, web/modules/custom/maybe_forms/src/Form/FarmForm.php, web/modules/custom/maybe_forms/src/Services/AccountService.php, web/modules/custom/maybe_forms/src/Services/FarmService.php
add form add farm both create account and farm
=> feat: create form farm

web/modules/custom/maybe_forms/maybe_forms.module, web/modules/custom/maybe_forms/maybe_forms.routing.yml, web/modules/custom/maybe_forms/src/Form/CustomerForm.php
create accounts for customers
CU-865d2cb9u
=> feat: add form create customer

config/core.entity_form_display.commerce_product.default.default.yml, config/core.entity_view_display.commerce_product.default.default.yml, config/core.extension.yml, config/field.field.commerce_product.default.field_isfeature.yml, config/field.storage.commerce_product.field_isfeature.yml, config/views.view.farmers_list.yml, web/modules/custom/farm_page/farm_page.module, web/modules/custom/farm_page/farm_page.services.yml, web/modules/custom/farm_page/src/Controller/FarmPageController.php, web/modules/custom/farm_page/src/Services/FarmPageService.php, web/modules/custom/farm_page/templates/farm-homepage.html.twig
create fields for farm and product to design farm homepage and product details page
CU-865d32kjk
=> feat: set up farm and product fields

composer.json, composer.lock, config/config_perms.custom_perms_entity.administer_account_settings.yml, config/config_perms.custom_perms_entity.administer_date_time.yml, config/config_perms.custom_perms_entity.administer_error_logs.yml, config/config_perms.custom_perms_entity.administer_file_system.yml, config/config_perms.custom_perms_entity.site_administer_customer_form.yml, config/config_perms.custom_perms_entity.site_administer_customer_form_edit.yml, config/config_perms.custom_perms_entity.site_administer_farm_form.yml, config/core.extension.yml, config/user.role.site_admin.yml, config/views.view.farmers_list.yml
set permission for site admin to manage farm and customer account
865d2c7p0
=> feat: setup admin account management

web/modules/custom/farm_page/css/farm-page.css, web/modules/custom/farm_page/farm_page.module, web/modules/custom/farm_page/src/Controller/FarmPageController.php, web/modules/custom/farm_page/templates/farm-homepage.html.twig
get date and display farm intro
CU-865d3gqqy
=> feat: create farm intro

web/modules/custom/farm_page/css/farm-page.css, web/modules/custom/farm_page/templates/farm-homepage.html.twig
create ui product by category
CU-865d3njbp
=> feat: create products by category ui

config/field.storage.commerce_store.field_products_by_category.yml, web/modules/custom/farm_page/css/farm-page.css, web/modules/custom/farm_page/src/Controller/FarmPageController.php, web/modules/custom/farm_page/src/Services/FarmPageService.php, web/modules/custom/farm_page/templates/farm-homepage.html.twig
build structure to get products infomation by category in order to display on UI
CU-865d3njbn
=> feat: build-structure-to-display-products-by-categories

web/modules/custom/farm_page/templates/farm-homepage.html.twig
render data at styled html code
CU-865d44cej
=> feat: matching structure and styling

web/modules/custom/farm_page/css/farm-page.css, web/modules/custom/farm_page/css/list-farm.css, web/modules/custom/farm_page/templates/farm-homepage.html.twig
=> fix: config size image product

web/modules/custom/farm_page/css/effect.css, web/modules/custom/farm_page/css/farm-page.css, web/modules/custom/farm_page/farm_page.libraries.yml, web/modules/custom/farm_page/src/Controller/FarmPageController.php, web/modules/custom/farm_page/templates/farm-homepage.html.twig
get data and create ui contact info
CU-865d3nggy
=> feat: create farm contact info

config/commerce_checkout.commerce_checkout_flow.default.yml, config/core.entity_view_display.commerce_product_variation.default.summary.yml, config/core.entity_view_mode.commerce_product_variation.summary.yml, config/core.extension.yml, config/user.role.anonymous.yml, config/user.role.authenticated.yml, config/views.view.commerce_checkout_order_summary.yml
enable checkout feature to complete checkout flow
CU-865d4aubq
=> feat: add flow view product and checkout

web/modules/custom/farm_page/css/farm-product.css, web/modules/custom/farm_page/farm_page.libraries.yml, web/modules/custom/farm_page/farm_page.module, web/modules/custom/farm_page/farm_page.routing.yml, web/modules/custom/farm_page/src/Controller/FarmPageController.php, web/modules/custom/farm_page/src/Services/FarmPageService.php, web/modules/custom/farm_page/templates/farm-homepage.html.twig, web/modules/custom/farm_page/templates/farm-product.html.twig
get all product of farm and filter by category
CU-865czvrt8
=> feat: view product list per store

web/modules/custom/farm_page/css/farm-product.css
fix css list product
CU-865d4m2n0
=> fix: fix display list products

config/core.entity_view_display.commerce_product.default.default.yml
modify config file in order to synchronize config on dev site
CU-865d4m3bx
=> fix: fix config synchronize-bug

web/modules/custom/farm_page/css/effect.css, web/modules/custom/farm_page/src/Services/FarmPageService.php
add function count characters in a string
CU-865d4mh2e
=> fix: ui description

web/modules/custom/farm_page/css/farm-page.css, web/modules/custom/farm_page/css/list-farm.css
remove padding and border when hover
CU-865d4pw12
=> fix: fix hover product item

config/commerce_checkout.commerce_checkout_flow.default.yml, config/core.entity_form_display.commerce_store.online.default.yml, config/core.entity_view_display.commerce_store.online.default.yml, config/field.field.commerce_store.online.field_image_front_page.yml, config/field.storage.commerce_store.field_image_front_page.yml, config/views.view.commerce_checkout_order_summary.yml, web/modules/custom/farm_page/src/Controller/FarmPageController.php, web/modules/custom/farm_page/src/Services/FarmPageService.php
add field and fix function get url image of farm
CU-865d4cryj
=> fix: add field image front page of farm

web/modules/custom/farm_page/css/list-farm.css, web/modules/custom/farm_page/farm_page.libraries.yml, web/modules/custom/farm_page/farm_page.module, web/modules/custom/farm_page/farm_page.routing.yml, web/modules/custom/farm_page/js/list-farm.js, web/modules/custom/farm_page/src/Controller/FarmPageController.php, web/modules/custom/farm_page/src/Services/FarmPageService.php, web/modules/custom/farm_page/templates/farm-page-views-farms.html.twig, web/modules/custom/farm_page/templates/list-farm.html.twig
add ajax when search farm
CU-865d4w87e
=> feat: add search to list of farm

composer.json, composer.lock, config/commerce_checkout.commerce_checkout_flow.default.yml, config/commerce_checkout.commerce_checkout_flow.shipping.yml, config/commerce_order.commerce_order_type.default.yml, config/commerce_product.commerce_product_variation_type.default.yml, config/commerce_shipping.commerce_package_type.default.yml, config/commerce_shipping.commerce_shipment_type.default.yml, config/core.entity_form_display.commerce_order.default.default.yml, config/core.entity_form_display.commerce_product_variation.default.default.yml, config/core.entity_form_display.commerce_shipment.default.checkout.yml, config/core.entity_form_display.commerce_shipment.default.default.yml, config/core.entity_form_mode.commerce_shipment.checkout.yml, config/core.entity_form_mode.profile.shipping.yml, config/core.entity_view_display.commerce_order.default.default.yml, config/core.entity_view_display.commerce_order.default.user.yml, config/core.entity_view_display.commerce_product_variation.default.cart.yml, config/core.entity_view_display.commerce_product_variation.default.default.yml, config/core.entity_view_display.commerce_product_variation.default.summary.yml, config/core.entity_view_display.commerce_shipment.default.checkout.yml, config/core.entity_view_display.commerce_shipment.default.default.yml, config/core.entity_view_display.commerce_shipment.default.user.yml, config/core.entity_view_mode.commerce_shipment.checkout.yml, config/core.entity_view_mode.commerce_shipment.user.yml, config/core.extension.yml, config/field.field.commerce_order.default.shipments.yml, config/field.field.commerce_product_variation.default.weight.yml, config/field.storage.commerce_order.shipments.yml, config/field.storage.commerce_product_variation.weight.yml, config/views.view.order_shipments.yml
complete checkout flow by adding shipping method and shipping fee per order
CU-865czvrv1
=> feat: proceed payment

config/commerce_checkout.commerce_checkout_flow.shipping.yml, config/commerce_shipping.commerce_shipment_type.default.yml, config/core.entity_form_display.commerce_store.online.default.yml, config/core.entity_view_display.commerce_shipment.default.checkout.yml, config/core.entity_view_display.commerce_shipment.default.user.yml, config/core.entity_view_display.commerce_store.online.default.yml, config/views.view.order_shipments.yml, web/modules/custom/farm_page/css/farm-page.css, web/modules/custom/farm_page/css/farm-product.css, web/modules/custom/farm_page/css/list-farm.css, web/modules/custom/farm_page/farm_page.module, web/themes/custom/maybe_farm/css/maybe_farm.css
add css to view form order
CU-865czvrug
=> feat: edit view form order

web/modules/custom/farm_page/css/farm-page.css, web/themes/custom/maybe_farm/css/maybe_farm.css, web/themes/custom/maybe_farm/templates/commerce-product.html.twig
add class to display correctly
CU-865d55cn6
=> fix: optimize css code

config/user.role.customer.yml, web/modules/custom/farm_page/farm_page.permissions.yml, web/modules/custom/farm_page/farm_page.routing.yml, web/themes/custom/maybe_farm/templates/commerce-product.html.twig
add permission to farm page module
CU-865d5b9p4
=> fix: change permission

web/themes/custom/maybe_farm/templates/commerce-product.html.twig
small change to keep product name stay in center of page
CU-865d55cn6
=> fix: adjust-product-details-name-position
